version: '3.8'

services:
  java-app:
    build: .
    container_name: java_app
    ports:
      - "8081:8080"
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:8
    container_name: mysql_db
    environment:
      MYSQL_DATABASE: cdweb
      MYSQL_ROOT_PASSWORD: 123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
